/***
 * This file contains the mapping of GrandMA3 keys to their corresponding labels
 * key = key code
 * value = label
 *
 * the keys are beeing used to generate the Quickeys and TouchOSC commands
 */

export default {
  PREV: "Prev",
  SET: "Set",
  SELFIX: "SelFix",
  PAUSE: "Pause",
  GOBACK: "Go-",
  GO: "Go+",
  NEXT: "Next",
  UP: "Up",
  DOWN: "Down",
  HIGHLIGHT: "Highlt",
  SOLO: "Solo",
  FREEZE: "Freeze",
  PREVIEW: "Prvw",
  BLIND: "Blind",
  USER1: "U1",
  USER2: "U2",
  PAGE_UP: "Page+",
  PAGE_DOWN: "Page-",
  ON: "On",
  MOVE: "Move",
  DELETE: "Delete",
  STOMP: "Stomp",
  SELECT: "Select",
  FIXTURE: "Fixture",
  PRESET: "Preset",
  EDIT: "Edit",
  UPDATE: "Update",
  OFF: "Off",
  COPY: "Copy",
  ALIGN: "Align",
  HELP: "Help",
  GOTO: "Goto",
  CHANNEL: "Channel",
  SEQUENCE: "Sequ",
  ASSIGN: "Assign",
  // X1 - X16 === executors 291 - 298 & 191 - 198
  XKEYS: "Xkeys",
  MENU: "Menu",
  LIST: "List",
  DEF_PAUSE: "Pause",
  DEF_GO: "Go+",
  DEF_GOBACK: "Go-",
  MA1: "MA",
  LEARN: "Learn",
  GOBACKFAST: "<<<",
  GOFAST: ">>>",
  GROUP: "Group",
  CUE: "Cue",
  TIME: "Time",
  STORE: "Store",
  MA2: "MA",
  SLASH: "/",
  PLEASE: "Please",
  NUM0: "0",
  DOT: ".",
  IF: "If",
  AT: "At",
  NUM1: "1",
  NUM2: "2",
  NUM3: "3",
  NUM4: "4",
  NUM5: "5",
  NUM6: "6",
  NUM7: "7",
  NUM8: "8",
  NUM9: "9",
  PLUS: "+",
  THRU: "Thru",
  MINUS: "-",
  OOPS: "Oops",
  ESC: "Esc",
  CLEAR: "Clear",
  FULL: "Full",
  // MA key maps
  CLONE: "Clone",
  // Link, seems to be useless since its not described in the manual
  GRID: "Grid",
  LAYOUT: "Layout",
  STEP: "Step",
  TIMECODE: "TC",
  VIEW: "View",
  DMX: "DMX",
  PHASER: "Phaser",
  MACRO: "Macro",
  PAGE: "Page",
  EXECUTOR: "Exec",
  FIX: "Fix",
  TOP: "Top",
  TEMP: "Temp",
  RATE1: "Rate1",
  BLACK: "Black",
  FLASH: "Flash",
  ASTERISK: "*",
  // Keys without physical equivalents
  DOUBLE_SPEED: null,
  FLIP: null,
  HALF_SPEED: null,
  KILL: null,
  LOAD: null,
  LOWLIGHT: null,
  NEXT_STEP: null,
  NEXT_X: null,
  NEXT_Y: null,
  NEXT_Z: null,
  PREV_STEP: null,
  PREV_X: null,
  PREV_Y: null,
  PREV_Z: null,
  RESET_MATRICKS: null,
  SWAP: null,
  TOGGLE: null,
  TOGGLE_MATRICKS: null,
  TOGGLE_STEP: null,
} as const;
